# Generated by Django 3.1 on 2021-01-13 16:39

import cloudinary.models
import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_assistant', '0005_auto_20210107_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='Archivo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 12, 39, 12, 514674)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Cedula',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 11', regex='^.{11}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FechaNacimiento',
            field=models.DateField(default=datetime.date(2021, 1, 13)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 16, 39, 12, 509678, tzinfo=utc)),
        ),
    ]
